### ISSUE TITLE
Maquettes

### ISSUE THREAD

**Issue by HaygieLagarde** [HaygieLagarde/php-si#2]
- [ ] page principale
- [x] formulaire

**Comment by victor-stef** [comment]
![maquette-homepage-marvel](https://cloud.githubusercontent.com/assets/22913615/21142266/a5bf8516-c141-11e6-8dca-623f5be2fc53.png)
![maquette-personnage-marvel](https://cloud.githubusercontent.com/assets/22913615/21142267/a5c7b92a-c141-11e6-8763-72e9721f50b5.png)

**Comment by victor-stef** [comment]
Done
